import { useEffect } from 'react';
import { BarChart3, CalendarDays, CheckCircle2, Clock3, History, XCircle } from 'lucide-react';
import { useMedicines } from '../contexts/MedicinesContext';
import { useIntakes } from '../contexts/IntakesContext';
import { EmptyState } from '../components/UI/EmptyState/EmptyState';
import './Pages.css';

const dateTime = (value: string) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
export const SchedulePage = () => { const { medicines } = useMedicines(); return <section className="page"><div className="page__heading"><div><p className="page__eyebrow">План на сегодня</p><h1>Расписание</h1><p>Регулярные напоминания по всем активным лекарствам.</p></div></div><div className="schedule-list">{medicines.filter(m => m.isActive).flatMap(m => m.times.map(time => ({m, time}))).sort((a,b) => a.time.localeCompare(b.time)).map(({m,time}) => <article className="schedule-item" key={`${m.id}-${time}`}><time>{time}</time><span style={{background:m.color}}/><div><h2>{m.name}</h2><p>{m.quantity} {m.quantityUnit} · {m.instruction}</p></div></article>)}</div></section> };
export const HistoryPage = () => { const { intakes, loading, getAllIntakes } = useIntakes(); const { getMedicineById } = useMedicines(); useEffect(() => { void getAllIntakes(); }, []); return <section className="page"><div className="page__heading"><div><p className="page__eyebrow">Ваши отметки</p><h1>История приёмов</h1><p>Просматривайте выполненные и пропущенные приёмы.</p></div></div>{loading ? <div className="page__loading">Загружаем историю…</div> : intakes.length ? <div className="history-list">{[...intakes].sort((a,b)=>b.scheduledTime.localeCompare(a.scheduledTime)).map(intake => <article className="history-item" key={intake.id}><span className={`status-icon status-icon--${intake.status}`}>{intake.status === 'taken' ? <CheckCircle2/> : intake.status === 'skipped' ? <XCircle/> : <Clock3/>}</span><div><h2>{getMedicineById(intake.medicineId)?.name ?? 'Удалённое лекарство'}</h2><p>{dateTime(intake.scheduledTime)}</p></div><strong>{intake.status === 'taken' ? 'Принято' : intake.status === 'skipped' ? 'Пропущено' : intake.status === 'missed' ? 'Не принято' : 'Запланировано'}</strong></article>)}</div> : <EmptyState icon={<History size={42}/>} title="История пока пуста" description="Отмечайте приёмы на главной странице, и они появятся здесь."/>}</section> };
export const StatisticsPage = () => { const { intakes, getAllIntakes, getStatistics } = useIntakes(); useEffect(() => { void getAllIntakes(); }, []); const s = getStatistics(); return <section className="page"><div className="page__heading"><div><p className="page__eyebrow">За всё время</p><h1>Статистика</h1><p>Следите за регулярностью приёма лекарств.</p></div></div><div className="stat-hero"><BarChart3 size={32}/><div><strong>{s.percentage}%</strong><span>соблюдение расписания</span></div></div><div className="stats-grid"><article><CheckCircle2/><strong>{s.taken}</strong><span>Принято</span></article><article><XCircle/><strong>{s.skipped}</strong><span>Пропущено</span></article><article><Clock3/><strong>{s.missed}</strong><span>Не принято</span></article><article><CalendarDays/><strong>{s.total}</strong><span>Всего приёмов</span></article></div>{!intakes.length && <p className="muted">Когда появятся отметки, здесь будет подробная статистика.</p>}</section> };
