import { useEffect, useState } from 'react';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import type { Medicine } from '../types';
import { useMedicines } from '../contexts/MedicinesContext';
import { useToast } from '../contexts/ToastContext';
import { Button } from '../components/Button/Button';
import './Pages.css';

const colors = ['#6A4BB5', '#3B82F6', '#10B981', '#F59E0B', '#EF4444'];
const defaults: Omit<Medicine, 'id' | 'createdAt' | 'updatedAt'> = { name: '', description: '', dosage: 1, dosageUnit: 'мг', quantity: 1, quantityUnit: 'таблетка', instruction: '', color: colors[0], times: ['09:00'], frequency: 'Каждый день', reminderBefore: 15, isActive: true };
export const MedicineFormPage = () => {
 const { id } = useParams(); const isEdit = Boolean(id); const navigate = useNavigate(); const { getMedicineById, createMedicine, updateMedicine } = useMedicines(); const { showToast } = useToast();
 const [form, setForm] = useState(defaults); const [saving, setSaving] = useState(false);
 useEffect(() => { const medicine = id ? getMedicineById(id) : undefined; if (medicine) { const { id: _, createdAt: __, updatedAt: ___, ...data } = medicine; setForm(data); } }, [id, getMedicineById]);
 const change = <K extends keyof typeof form>(key: K, value: typeof form[K]) => setForm((current) => ({...current, [key]: value}));
 const save = async (event: React.FormEvent) => { event.preventDefault(); if (!form.name.trim() || !form.instruction.trim()) { showToast('Заполните название и инструкцию', 'warning'); return; } setSaving(true); try { if (id) await updateMedicine(id, form); else await createMedicine(form); showToast(isEdit ? 'Изменения сохранены' : 'Лекарство добавлено', 'success'); navigate('/medicines'); } finally { setSaving(false); } };
 return <section className="page form-page"><button className="back-link" onClick={() => navigate(-1)}><ArrowLeft size={18}/>Назад</button><div className="page__heading"><div><p className="page__eyebrow">{isEdit ? 'Карточка препарата' : 'Новый препарат'}</p><h1>{isEdit ? 'Редактировать лекарство' : 'Добавить лекарство'}</h1></div></div><form className="medicine-form" onSubmit={save}><label>Название<input value={form.name} onChange={(e) => change('name', e.target.value)} placeholder="Например, Омега-3" required/></label><label>Описание<input value={form.description} onChange={(e) => change('description', e.target.value)} placeholder="Для чего нужен препарат"/></label><div className="form-grid"><label>Дозировка<input type="number" min="0" value={form.dosage} onChange={(e) => change('dosage', Number(e.target.value))}/></label><label>Единица<select value={form.dosageUnit} onChange={(e) => change('dosageUnit', e.target.value as Medicine['dosageUnit'])}><option>мг</option><option>мл</option><option>г</option><option>мкг</option></select></label><label>Количество<input type="number" min="1" value={form.quantity} onChange={(e) => change('quantity', Number(e.target.value))}/></label><label>Единица количества<select value={form.quantityUnit} onChange={(e) => change('quantityUnit', e.target.value as Medicine['quantityUnit'])}><option>таблетка</option><option>капсула</option><option>мл</option><option>доза</option><option>шт</option></select></label></div><label>Инструкция<input value={form.instruction} onChange={(e) => change('instruction', e.target.value)} placeholder="Например, после еды" required/></label><label>Частота<select value={form.frequency} onChange={(e) => change('frequency', e.target.value as Medicine['frequency'])}><option>Каждый день</option><option>По определённым дням</option><option>По необходимости</option></select></label><fieldset><legend>Время приёма</legend>{form.times.map((time, index) => <div className="time-row" key={`${time}-${index}`}><input type="time" value={time} onChange={(e) => change('times', form.times.map((item, itemIndex) => itemIndex === index ? e.target.value : item))}/>{form.times.length > 1 && <button type="button" onClick={() => change('times', form.times.filter((_, itemIndex) => itemIndex !== index))} aria-label="Удалить время"><Trash2 size={18}/></button>}</div>)}<button type="button" className="text-button" onClick={() => change('times', [...form.times, '12:00'])}><Plus size={17}/>Добавить время</button></fieldset><fieldset><legend>Цвет карточки</legend><div className="color-options">{colors.map((color) => <button type="button" key={color} className={form.color === color ? 'selected' : ''} onClick={() => change('color', color)} style={{background: color}} aria-label={`Выбрать цвет ${color}`}/>)}</div></fieldset><Button type="submit" size="lg" fullWidth disabled={saving}>{saving ? 'Сохраняем…' : 'Сохранить'}</Button></form></section>;
};
